networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  bots:
    env_file: .env.bots
    build:
      context: ./
      dockerfile: ./ab-bot/Dockerfile
    depends_on:
      - server
    environment:
      - NODE_ENV=production
      - SERVER_IP=172.20.0.5
    networks:
      frontend:
        ipv4_address: 172.20.0.10

  server:
    env_file: .env.server
    build:
      context: ./ab-server
      dockerfile: Dockerfile
    ports:
      - '3501:3501'
    environment:
      - NODE_ENV=production
      - BOTS_IP=172.20.0.10
    networks:
      frontend:
        ipv4_address: 172.20.0.5
    volumes:
      - ./logs:/app/logs

  frontend:
    build:
      context: ./
      dockerfile: ./ab-frontend/Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - server
    networks:
      frontend:
        ipv4_address: 172.20.0.8
