version: '3'
services:
  server:
    env_file: .env.server
    build:
      context: ./ab-server
      dockerfile: Dockerfile
    ports:
      - '3501:3501'
    environment:
      - NODE_ENV=production

  # frontend:
  #   build:
  #     context: ./airmash-frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - server

  # bot:
  #   build:
  #     context: ./ab-bot
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - server
  #   environment:
  #     - SERVER_HOST=server
  #     - SERVER_PORT=3501
